*** Settings ***

Library                           String

Resource                         ../../../../Keywords/UI/More/Assets/vendors.robot
Resource                          ../../../../Keywords/UI/Helpers/table.robot
Resource                          ../../../../Keywords/UI/moremenu.robot

Force Tags                        Vendors

Suite Setup                       Open Browser to login page
Suite Teardown                    Close browser

*** Test Cases ***

Verify Add Vendor
    [Tags]                        AddVendor
    [Documentation]               Verify add Vendor
    [Setup]     run keywords      Login:
    ...         AND               Navigate to Vendors
    ${ID}                         generate random string
    ${NAME}                       generate random string
    ${CONTACT}                    generate random string  12  [NUMBERS]
    ${EMAIL}                      Generate random Email
    ${WEBSITE}                    Generate random Website
    ${ADRESS}                     generate random string
    Add Vendor:                   ${NAME}  ${ID}   ${CONTACT}   ${EMAIL}    ${WEBSITE}  ${ADRESS}
    ${MSG}                        Get toast message
    should be equal               ${MSG}   ${MSG_SUCCESSFULLY_SAVED}
    Is item in the table:         ${NAME}
    Delete Vendor:                ${ID}    ${NAME}
    [Teardown]                    Logout

Verify Add Vendor with autogenerated ID
    [Tags]                        AddVendor
    [Documentation]               Verify add Vendor using auto generated ID
    [Setup]     run keywords      Login:
    ...         AND               Navigate to Vendors
    ${NAME}                       generate random string
    ${CONTACT}                    generate random string  12  [NUMBERS]
    ${EMAIL}                      Generate random Email
    ${WEBSITE}                    Generate random Website
    ${ADRESS}                     generate random string
    ${ID}=      Add Vendor:       ${NAME}   CONTACT=${CONTACT}   EMAIL=${EMAIL}    WEBSITE=${WEBSITE}  ADRESS=${ADRESS}
    ${MSG}                        Get toast message
    should be equal               ${MSG}   ${MSG_SUCCESSFULLY_SAVED}
    Is item in the table:         ${ID}
    [Teardown]                    Logout

Verify Add Vendor with autogenerated ID - search by ID and Reset the search
    [Tags]                        AddVendor
    [Documentation]              Verify add Vendor using auto generated ID
    [Setup]     run keywords      Login:
    ...         AND               Navigate to Vendors
    ${NAME}                       generate random string
    ${CONTACT}                    generate random string  12  [NUMBERS]
    ${EMAIL}                      Generate random Email
    ${WEBSITE}                    Generate random Website
    ${ADRESS}                     generate random string
    ${ID}=      Add Vendor:       ${NAME}   CONTACT=${CONTACT}   EMAIL=${EMAIL}    WEBSITE=${WEBSITE}  ADRESS=${ADRESS}
    ${MSG}                        Get toast message
    should be equal               ${MSG}   ${MSG_SUCCESSFULLY_SAVED}
    Filter brand by ID and Name:  ${ID}  ${NAME}
    Reset filter
    [Teardown]                    Logout

