*** Settings ***

Resource                                    ../../../../Keywords/UI/More/Assets/ViewAssets.robot

Force Tags                                  Assets
Suite Setup                                 Open Browser to login page
Suite Teardown                              Close all browsers

*** Variables ***
${HEADER_TITLE_ID}                          id=addSessionTitle
${HEADER_TITLE_TEXT}                        Asset Details

*** Test Cases ***

Add new Asset with autogenerated id - All Fields
    [Documentation]                             Adds new Asset.
    [Tags]                                      P1
    [Setup]  run keywords                       Login:
    ...         AND                             Navigate to ViewAssets
    ...         AND                             Select frame  ${iFrame}
    Mouse over                                  ${BTN_ADD}
    Add Asset - Verify Add Asset button tooltip
    Click on Add button
    element text should be                      ${HEADER_TITLE_ID}  ${HEADER_TITLE_TEXT}
    Add Asset:  192425008   brand=Dell  vendor=Dell Computer Corp.  model=Dell008     category=USB Devices        location=Sample Location        acquired=10/October/2020       warranty_starts=30/September/2018       warranty_ends=3/August/2022      description=Testing     status=Decommission     file=${FILE_ASSETS}    image=${IMAGE_ASSETS}
    [Teardown]                                  Logout

Add new Asset with only mandatory fields
    [Documentation]                             Adds new Asset.
    [Tags]                                      P1
    [Setup]  run keywords                       Login:
    ...         AND                             Navigate to ViewAssets
    ...         AND                             Select frame  ${iFrame}
    Mouse over                                  ${BTN_ADD}
    Add Asset - Verify Add Asset button tooltip
    Click on Add button
    element text should be                      ${HEADER_TITLE_ID}  ${HEADER_TITLE_TEXT}
    Add Asset:  srl12233   18741024766
    [Teardown]                                  Logout
